### ISSUE TITLE
Speed benchmarks with `async_get`?

### ISSUE THREAD

**Issue by ThinksFast** [daijro/hrequests#17]
Hey, I am using `async_get` with `hrequests.imap_enum(reqs)` to scrape 100 URLs at a time.  The `readme` says this should be blazing fast, but I'm not sure what that means.  It's currently taking 3-5 minutes, and that does not include a render step.

Is that approximately the amount of time it should take?  I was thinking it'd be a lot faster since it's just a request and not a rendering.  Here's the code I'm currently using. The `rows` variable is 100 DB records, specifically a SQL Alchemy `RowMapping` object.

```
reqs = [hrequests.async_get(r.url) for r in rows]

responses = []

for index, resp in hrequests.imap_enum(reqs):
    if resp:
        with open(f'{directory}/{index}.pickle', 'wb') as file:
            pickle.dump(resp, file)
        responses.append({"url": resp.url, "resp": resp})
        
    else:
        print(f'No response for {index}')
```

**Comment by daijro** [comment]
Hello,
By "*blazing fast*", I mean that I am leveraging *gevent* rather than threading for concurrency. This means that the OS does not have to register a new thread for each request, making hrequests faster, more scalable, and resource friendly.

As for the slowdowns due the `async_get` method, this might be due to limitations with the browser fingerprint being used for the backend [TLS client](https://github.com/bogdanfinn/tls-client).

I would suggest building a [session](https://github.com/daijro/hrequests/#sessions) as to not rebuild the connections for each request of the website you are scraping, and testing the response time of whether the Firefox or Chrome sessions perform faster for your specific website. Some browser fingerprints may perform slower than others on certain pages.

Thanks!

**Comment by ThinksFast** [comment]
@daijro  Thanks for the idea.  I gave this a try, and it seems to be even slower.  I'm including some updated code below that includes a `render()` step.  The flow of this code is:  make a bunch of requests, try to render the responses and pickle the response to a local directory.  If the rendering fails, then pickle the unrendered response.

The behavior I observed with the code below is:

1. `hrequests` makes 50 requests at a time, as set by `size=50`.   Based on the timings, this is not done in parallel, it's done sequentially and synchronously.  It took 2 minutes and 20 seconds until the responses started rendering
2. Once the 50 requests are received, it will render each one individually using the `with resp.render() as page:` context manager.  Looking at my OS process manager, I see only one Chromium instance running in the background, rendering the responses.

Total time to process ~100 URLs was 10 minutes and 39 seconds.  I tried adding `nohup` to the request list, but the code executes immediately in 0 seconds and never shows a response.  Maybe I am using this wrong, I understand it's supposed to be a lazy request... is there a recommended way to wait for the responses to come in?  The docs just say `# Sometime later...`

Ex:  `reqs = [session.async_get(r.url, nohup=True) for r in rows]`

Here's the full code:
```
rows = await query_results(query)

def pickle_it(index: int, resp: hrequests.Response) -> None:
    with open(f'responses/{index}.pickle', 'wb') as file:
        pickle.dump(resp, file)

with hrequests.chrome.Session() as session:
    reqs = [session.async_get(r.url, nohup=True) for r in rows]

    for index, resp in hrequests.imap_enum(reqs, size=50):
        try:
            if resp:
                with resp.render() as page:
                    pickle_it(index, resp)

            else:
                print(f'No response for {index}')
                pickle_it(index, resp)

        except BrowserTimeoutException as exc:
            print(f"BrowserTimeoutException: {exc}")
            pickle_it(index, resp)
            continue

        except BrowserException as exc:
            print(f"BrowserException: {exc}")
            pickle_it(index, resp)
            continue

        except Exception as exc:
            print(f"Exception: {exc}")
            continue
```

**Comment by ThinksFast** [comment]
Not sure if this makes a difference, but I'm currently running this in a notebook and using python 3.11.4

**Comment by daijro** [comment]
I see what you mean.

It seems that in very large quantities of requests there is a noticeable slowdown. In `imap_enum`, responses are returned in sequential order, which is not intended. After some additional testing with the tls-client go library, it appears that gevent has slowdowns when handing foreign/external libraries. My apologies.

Going forward, I will transition to the go virtual threading library, or abandon gevent-like virtual threading altogether and use concurrent.futures.ThreadPoolExecutor.

Thank you!

---

Also to note, adding `nohup=True` causes it to fail because `nohup` is not a parameter for the async methods. Instead, it immediately returns an error, into the `exception_handler`, if one was specified.
I should instead directly return an exception when `async_get` is called rather than forwarding it into the exception handler. Thanks for letting me know.

**Comment by ThinksFast** [comment]
Thanks so much for looking into this and continuing work on the project, it really is quite a nice Python module!  Excited to see how it evolves.  

RE: `nohup`, if I'm reading the docs right, it's listed as a parameter for `async_get`.  Probably a copy/pasta issue, so wanted to mention it here for tracking.  😎

<img width="884" alt="image" src="https://github.com/daijro/hrequests/assets/114229148/e9fdd075-4926-4bbe-bbfd-46639c738795">

**Comment by daijro** [comment]
Hello,

This issue should be resolved in the v0.8.0 beta release.

Hrequests' concurrency now makes use of goroutines through a local Golang bridge server, which runs significantly faster:

https://github.com/daijro/hrequests/assets/72637910/958e00e2-82a2-44d2-a753-c5c515e9e6a6

Feel free to try it out and let me know how it works for you. Thanks!

**Comment by ThinksFast** [comment]
Certainly looks fast!  Is the 3rd line supposed to use the `sess` instead of `hrequests`?  Or does creating the `sess` serve a different purpose?

I'm testing this on my local right now with the same code from [this comment](https://github.com/daijro/hrequests/issues/17#issuecomment-1732624569).  Looks like the headless renders are done sequentially... I'm 5 minutes in and about 50 pages rendered.  Is there a way to speed this up in the current codebase?

**Comment by daijro** [comment]
Hello,

Yes, the 3rd like was supposed to make use of the session with `sess` instead of `hrequests`. My bad, this was a typo.

---

The reason the code you provided is rendering responses synchronously is due to how `hrequests.imap_enum` works.

`imap_enum` is an iterator that fetches and yields the responses of requests as they come in. However, the way the code processes each response (i.e., the body of the for loop) is done synchronously. 

In your current codebase, although the requests are asynchronous, the processing of each response is not. This rendering of your loop would be triggered for each response as they come in, one after another. This causes the rendering to be ran synchronously.

```py
with resp.render() as page:
    pickle_it(index, resp)
```

If you want the responses to be rendered concurrently as they come in, you'll need to handle the rendering in separate threads or processes to run them concurrently.

**Comment by ThinksFast** [comment]
Got it, thanks for the feedback, really helpful
