### ISSUE TITLE
Please update Playwright-python to 1.40 for Python 3.12 compatibility

### ISSUE THREAD

**Issue by TudorAndrei** [daijro/hrequests#49]
Based on https://github.com/microsoft/playwright-python/issues/2096

As of now, hrequest[all] doesn't work for python 3.12, due to the fact that greenlet==2.0.2 can't be installed.

**Comment by tobwen** [comment]
For anyone, who wants to try it out:

``` sh
pip install git+https://github.com/TudorAndrei/hrequests.git@patch-1#egg=hrequests[all]
```

**Comment by baderdean** [comment]
Hello, is there any reason why the linked PR hasn't been merged?

**Comment by daijro** [comment]
> Hello, is there any reason why the linked PR hasn't been merged?

Hello,

The PR hasn't been merged because it breaks some aspects of hrequests. Since playwright 1.34.0, there have been differences in how Errors are imported/handled, and how extensions are added to Chromium browsers in Playwright ([see here](https://github.com/daijro/hrequests/issues/39#issuecomment-2028227977)). 

I will go ahead and merge the PR, but unfortunately I cannot publish a stable release to Pypi until I fix the implementation issues that come with it.

**Comment by baderdean** [comment]
Hello & thanks @daijro

I wanted to know what aspects of hrequests does this merge break?
Especially if it affects javascript.

regards
