### ISSUE TITLE
Process finished with exit code 137 (interrupted by signal 9: SIGKILL)

### ISSUE THREAD

**Issue by petrsevcik** [daijro/hrequests#8]
My python crash when trying simple request

```
import hrequests

resp = hrequests.get('https://www.google.com')
```

I am using virtual env with python 3.9.6, Macbook with M2 chip. In pycharm interpreter or terminal, I get "Process finished with exit code 137 (interrupted by signal 9: SIGKILL)" (pycharm)  and apple report window appears with message that "python quit unexpectedly" This happens during import of the package

**Comment by daijro** [comment]
Figured out that the tls-client-xgo library does not work as intended on macOS.

This has been patched in [this commit](https://github.com/daijro/hrequests/commit/4e9a4fbcf5a829f1b91a2a52c345b9dd125d024e) and should be rolled out with v0.7.0.

**Comment by petrsevcik** [comment]
I've tried version 0.7.1 and 0.7.0 and the issue still persists.

**Comment by daijro** [comment]
> I've tried version 0.7.1 and 0.7.0 and the issue still persists. 

This is likely because the tls-client library hasn't been updated. Heres a fix:

1. Run `python3 -m pip uninstall hrequests -v`

2. Under `Would not remove (might be manually added)`, look for the full path to the file located under `site-packages/hrequests/bin/tls-client-xgo-1.6.0-darwin-arm64.dylib`.

3. Run `rm <full path to .dylib file>`.
